// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD367LW3wVmVmHsVhOBUqsgipBRjoSxxxs',
    appId: '1:517334057508:web:595a67865d78ef4c10ceb1',
    messagingSenderId: '517334057508',
    projectId: 'skill-link-1c0c3',
    authDomain: 'skill-link-1c0c3.firebaseapp.com',
    storageBucket: 'skill-link-1c0c3.firebasestorage.app',
    measurementId: 'G-J6M5BZ5BXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT9fWa5-9xnSvtsxr0pumOJJfT_5wAyuU',
    appId: '1:517334057508:android:f0127eb9233bb3f710ceb1',
    messagingSenderId: '517334057508',
    projectId: 'skill-link-1c0c3',
    storageBucket: 'skill-link-1c0c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FvMXlf2VzPylz9t_uU_V4QjOu4E0Veg',
    appId: '1:517334057508:ios:d73a94baaec1a6f310ceb1',
    messagingSenderId: '517334057508',
    projectId: 'skill-link-1c0c3',
    storageBucket: 'skill-link-1c0c3.firebasestorage.app',
    iosBundleId: 'com.example.skillLinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-FvMXlf2VzPylz9t_uU_V4QjOu4E0Veg',
    appId: '1:517334057508:ios:d73a94baaec1a6f310ceb1',
    messagingSenderId: '517334057508',
    projectId: 'skill-link-1c0c3',
    storageBucket: 'skill-link-1c0c3.firebasestorage.app',
    iosBundleId: 'com.example.skillLinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD367LW3wVmVmHsVhOBUqsgipBRjoSxxxs',
    appId: '1:517334057508:web:c0c84017af6f2b1210ceb1',
    messagingSenderId: '517334057508',
    projectId: 'skill-link-1c0c3',
    authDomain: 'skill-link-1c0c3.firebaseapp.com',
    storageBucket: 'skill-link-1c0c3.firebasestorage.app',
    measurementId: 'G-TMXXTPQVHJ',
  );
}
